/**
 * Cloudflare Pages Functions entry point.
 * Imports from the React Router server build output (build/server/index.js),
 * which is generated by `npm run build` before this file is bundled by wrangler.
 */
import { createPagesFunctionHandler } from "@react-router/cloudflare";

// This import is resolved after `npm run build` creates build/server/index.js.
// @ts-expect-error — generated at build time
import * as build from "../build/server/index.js";

export const onRequest: PagesFunction<Env> = createPagesFunctionHandler({
  build,
});
